import '@/app/globals.css'

import Link from 'next/link'

import ThemeButton from '@/theme/ThemeButton'
import ThemeProviders from '@/theme/ThemeProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body >
        <ThemeProviders>
          {/* Header */}
          <header className='py-6'>
            <nav className=' flex items-center justify-between'>
              <ul className='flex gap-6'>
                <li>
                  <Link href='/'>Home</Link>
                </li>
              </ul>

              <ThemeButton  />
            </nav>
          </header>

          {/* Page */}
          <main>{children}</main>

          {/* Footer */}
          <footer></footer>
        </ThemeProviders>
      </body>
    </html>
  )
}