import "@/app/globals.css";

import ThemeProviders from "@/theme/ThemeProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SessionProviders from "@/session/SessionProviders";

export const metadata = {
  title: "Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProviders>
          <SessionProviders>
            {/* Header */}
            <Header />
            {/* Page */}
            <main>{children}</main>
            {/* Footer */}
            <Footer />
          </SessionProviders>
        </ThemeProviders>
      </body>
    </html>
  );
}
